//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.T_S = new HashSet<T_S>();
        }
    
        public int subject_id { get; set; }
        public string subject_Name { get; set; }
        public string subject_code { get; set; }
        public int classes_per_week { get; set; }
        public double total_grade { get; set; }
        public double year_wok { get; set; }
        public double final_exam_grade { get; set; }
        public int grade_ID { get; set; }
        public string type { get; set; }
        public string semester { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_S> T_S { get; set; }
    }
}
